# Muncher Marginal & Conditional Intuition

In [1]:
# Load the Pandas libraries with alias 'pd' 
# Load the Plotly Plotly library with alias 'py'
# Load the Plotly Graph Objects library with alias 'px'
import pandas as pd 
import chart_studio.plotly as py
import plotly.graph_objects as go
# Read data from file 'sample_semanai.csv' 
consumerData = pd.read_csv("sample_semanai.csv")

In [2]:
consumerData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46472 entries, 0 to 46471
Data columns (total 22 columns):
Unnamed: 0          46472 non-null int64
dia                 46472 non-null object
orden               46472 non-null int64
noPersonas          46472 non-null int64
terminal            46472 non-null object
accion              46472 non-null object
cantidad            46467 non-null float64
foodGroup           46467 non-null object
subGroup            46467 non-null object
keyFood             46183 non-null object
modificador         20738 non-null object
esModificador       46183 non-null object
idEncuesta          46472 non-null int64
cuenta              46472 non-null int64
mesa                46472 non-null int64
recomendacion       46472 non-null int64
company             42883 non-null object
ageRange            42883 non-null object
acknowledge         15788 non-null object
manager             43285 non-null float64
firstTime           43284 non-null float64
preferenceReason    42885 non-null object
dtypes: float64(3), int64(7), object(12)
memory usage: 7.8+ MB

In [22]:
pd.pivot_table(consumerData,values='cantidad',index='dia',columns='keyFood').fillna(0)

keyFood,BAS1,BAS10,BAS11,BAS12,BAS13,BAS14,BAS2,BAS3,BAS4,BAS5,...,bebi004,bebi005,bebi006,bebi01,bebi02,bebi03,mcl90004,mcl90005,mcl90009,mcla9006
dia,,,,,,,,,,,,,,,,,,,,,
domingo,1.020000,1.0,1.0,1.0,1.0,1.0,1.056452,1.0,1.000000,1.000000,...,1.125000,1.0,1.000000,1.0,1.0,1.000000,1.0,0.0,0.0,1.0
jueves,1.017964,1.0,0.0,1.0,1.0,1.0,1.058252,1.0,1.000000,1.000000,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,0.0,1.0,1.0,0.0
lunes,1.025559,0.0,0.0,1.0,1.0,0.0,1.032967,1.0,1.285714,1.000000,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.0,0.0,0.0,1.0
martes,1.012346,1.0,0.0,1.0,1.0,1.0,1.025000,1.0,1.000000,1.166667,...,1.111111,1.0,1.000000,0.0,1.0,1.000000,0.0,0.0,0.0,1.0
miércoles,1.037915,0.0,0.0,1.0,1.0,1.0,1.000000,1.0,1.000000,1.090909,...,1.000000,0.0,1.000000,1.0,1.0,1.285714,0.0,0.0,0.0,0.0
sábado,1.030909,0.0,0.0,1.0,1.0,1.0,1.024194,1.0,1.000000,1.000000,...,1.000000,1.0,1.000000,1.0,1.0,1.000000,1.0,0.0,0.0,0.0
viernes,1.030418,0.0,0.0,1.0,1.0,0.0,1.000000,1.0,1.000000,1.000000,...,1.000000,0.0,1.111111,1.0,1.0,1.000000,1.0,0.0,0.0,1.0

In [24]:
pd.pivot_table(consumerData,values='cantidad',index='keyFood',columns='ageRange').fillna(0)

ageRange   18 a 21   22 a 25   26 a 32   33 a 44  45 ó más  Menor a 17
keyFood
BAS1      1.041594  1.021111  1.014065  1.046332  1.010204    1.046729
BAS10     0.000000  0.000000  1.000000  1.000000  0.000000    0.000000
BAS11     1.000000  0.000000  0.000000  0.000000  0.000000    0.000000
BAS12     1.000000  1.000000  1.000000  1.000000  1.000000    0.000000
BAS13     1.000000  1.000000  1.000000  1.000000  1.000000    0.000000
...            ...       ...       ...       ...       ...         ...
bebi03    1.000000  1.000000  1.095238  1.000000  1.000000    1.000000
mcl90004  1.000000  1.000000  1.000000  0.000000  0.000000    1.000000
mcl90005  1.000000  0.000000  0.000000  0.000000  0.000000    0.000000
mcl90009  0.000000  0.000000  1.000000  0.000000  0.000000    0.000000
mcla9006  0.000000  1.000000  1.000000  1.000000  1.000000    0.000000

[347 rows x 6 columns]

In [25]:
pd.pivot_table(consumerData,values='cantidad',index='subGroup',columns='ageRange').fillna(0)

ageRange,18 a 21,22 a 25,26 a 32,33 a 44,45 ó más,Menor a 17
subGroup,,,,,,
BEBIDAS,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
BEBIDAS CON ALCOHOL,1.018727,1.013188,1.017181,1.006466,1.015337,1.027273
BEBIDAS SIN ALCOHOL,1.013874,1.011692,1.017857,1.020906,1.030612,1.005236
BEBIDAS SÚPER,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
BÁSICOS,1.031614,1.020040,1.011204,1.034091,1.006079,1.020619
CLÁSICOS,1.006629,1.006597,1.011621,1.007186,1.014035,1.006780
DESTILADOS,1.076923,1.102564,1.000000,1.000000,1.076923,1.000000
ENSALADAS,1.000000,1.000000,1.000000,1.000000,1.057143,1.000000
ENTRADAS,1.011628,1.000000,1.000000,1.008772,1.000000,1.000000
EXTRAS BARRA,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
EXTRAS COCINA,1.000000,1.010753,1.000000,1.000000,1.000000,1.000000
HAMBURGUESAS,1.039010,1.037029,1.033082,1.038961,1.039816,1.066781
"PAPAS, PAPAS Y MÁS PAPAS",1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
PASTAS,1.000000,1.000000,1.015038,1.000000,1.000000,1.000000
POSTRES,1.000000,1.004673,1.000000,1.000000,1.000000,1.000000
SANDWICHES,1.009009,1.000000,1.030457,1.011765,1.027027,1.000000

In [26]:
pd.pivot_table(consumerData,values='cantidad',index='keyFood',columns='modificador').fillna(0)

modificador,86 Alcohol,86Brocoli..,86Crema..,86E Cebolla morada,86E Elote amarillo,86E Queso cabra,86E Ranch jalapeño,86E Vinagreta balsámica,86H Aguacate,86H BBQ,...,Vaso Chelado,Vaso Clamato,Vaso Michelado,Vaso Munchero,Victoria,Victoria..,Vodka Smirnoff,Whisky Black & White,Ximena,Zacapa 23 D
keyFood,,,,,,,,,,,,,,,,,,,,,
DES01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DES02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DES03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
DES04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
DES05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
bebi03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mcl90004,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mcl90005,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mcl90009,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
mcla9006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0